spring.config.import: "configserver:"

spring:
  application.name: gateway
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 50
    uri: http://u:p@localhost:8888
    username: u
    password: p


---
spring.config.activate.on-profile: docker

spring:
  application.name: gateway
  cloud.config:
    failFast: true
    retry:
      initialInterval: 3000
      multiplier: 1.3
      maxInterval: 10000
      maxAttempts: 50
    uri: http://u:p@configserver:8888
    username: u
    password: p

#spring.cloud.config.uri: http://u:p@configserver:8888

